# Generated by Django 2.0.3 on 2018-06-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date']},
        ),
    ]
